// For determining applicable counties
export const MAX_RADIUS_IN_KM = 200;

// For seeding treatments
export const SEEDING_RATE_PER_ACRE_IN_POUNDS = 141;
export const NEONICOTINOID_SEEDING_COST_PER_POUND_IN_DOLLARS = 0.48; 
export const UNTREATED_SEEDING_COST_PER_ACRE_IN_DOLLARS = 0.36;

// For spraying treatments
const OUNCES_PER_GALLON = 128;
export const WARRIOR_II_SPRAYING_COST_PER_OUNCE_IN_DOLLARS = 285 / OUNCES_PER_GALLON;
export const WARRIOR_II_APPLICATION_RATE_PER_ACRE_IN_OUNCES = 1.92;
export const WARRIOR_II_SPRAYING_COST_PER_ACRE_IN_DOLLARS = WARRIOR_II_SPRAYING_COST_PER_OUNCE_IN_DOLLARS * WARRIOR_II_APPLICATION_RATE_PER_ACRE_IN_OUNCES;
export const WARRIOR_II_MACHINERY_COST_PER_ACRE_IN_DOLLARS = 4.39;

// Total treatment costs per acre & bushel price
export const NEONICOTINOID_SEED_MARGINAL_COST_PER_ACRE_IN_DOLLARS = SEEDING_RATE_PER_ACRE_IN_POUNDS * (NEONICOTINOID_SEEDING_COST_PER_POUND_IN_DOLLARS - UNTREATED_SEEDING_COST_PER_ACRE_IN_DOLLARS);
export const WARRIOR_II_TOTAL_COST_PER_ACRE_IN_DOLLARS = WARRIOR_II_SPRAYING_COST_PER_ACRE_IN_DOLLARS + WARRIOR_II_MACHINERY_COST_PER_ACRE_IN_DOLLARS;
export const COMBINED_TREATMENT_COST_PER_ACRE_IN_DOLLARS = NEONICOTINOID_SEED_MARGINAL_COST_PER_ACRE_IN_DOLLARS + WARRIOR_II_TOTAL_COST_PER_ACRE_IN_DOLLARS;
export const BUSHEL_PRICE_IN_DOLLARS = 5.30;